[package]
name = "timetable"
version = "0.1.0"
edition = "2021"
authors = ["Lugrim"]
repository = "https://github.com/Lugrim/timetable-language"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
